import pygame

# --- Constants ---
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60

# Colors
SKY_BLUE = (135, 206, 235)

# Player settings
PLAYER_WIDTH = 32
PLAYER_HEIGHT = 32
PLAYER_ACC = 0.5
GROUND_FRICTION = -0.1
AIR_FRICTION = -0.05
PLAYER_MAX_SPEED = 5
JUMP_STRENGTH = -12
GRAVITY = 0.8
ROTATION_SPEED = 10
BULLET_TIME_FACTOR = 0.5
STAFF_THROW_SPEED = 10
STAFF_ROTATION_SPEED = 10
STAFF_RETURN_SPEED = 5
TRAIL_DISTANCE_MULTIPLIER = 1
TRAIL_ROTATION_OFFSET = 0

# Staff settings

# World settings
TILE_SIZE = 40